services:
  - type: web
    name: mycontacts-api
    env: node
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
